# Sample Makefile

# Variables
PYTHON := python3
PIP := pip

# Targets and Rules
install:
	$(PIP) install -r ./requirements/requirements.txt
	$(PIP) install -r ./requirements/test_requirements.txt

format:
	$(PYTHON) -m black .

lint:
	$(PYTHON) -m flake8 .

test:
	$(PYTHON) -m pytest

all: install format lint test
